<?php

namespace App;

use App\Traits\SegmentUser;
use Illuminate\Database\Eloquent\Model;

class ClusterValue extends Model
{

    use SegmentUser;

    protected $fillable = [
                           'd1_married_couple_family',
                           'd1_d1_mfirst',
                           'd1_median_education_attained',
                           'd1_d5_mfirst',
                           'd1_median_family_household_income',
                           'd1_home_owner',
                           'd1_number_of_persons_in_living_unit',
                           'd1_child_hh_with_persons',
                           'd1_median_home_value',
                           'd1_urban_county_size_code',
                           'd1_pop_hispanic',
                           'd1_pop_asian',
                           'd1_combnd_mosaic_group',
                           'd1_d_est_inc_v5',
                           'd1_length_of_residence',
                           'd1_mor_home_pur_home_pur_1',

                           'd2_married_couple_family',
                           'd2_d1_mfirst',
                           'd2_median_education_attained',
                           'd2_d5_mfirst',
                           'd2_median_family_household_income',
                           'd2_home_owner',
                           'd2_number_of_persons_in_living_unit',
                           'd2_child_hh_with_persons',
                           'd2_median_home_value',
                           'd2_urban_county_size_code',
                           'd2_pop_hispanic',
                           'd2_pop_asian',
                           'd2_combnd_mosaic_group',
                           'd2_d_est_inc_v5',
                           'd2_length_of_residence',
                           'd2_mor_home_pur_home_pur_1',

                           'd3_married_couple_family',
                           'd3_d1_mfirst',
                           'd3_median_education_attained',
                           'd3_d5_mfirst',
                           'd3_median_family_household_income',
                           'd3_home_owner',
                           'd3_number_of_persons_in_living_unit',
                           'd3_child_hh_with_persons',
                           'd3_median_home_value',
                           'd3_urban_county_size_code',
                           'd3_pop_hispanic',
                           'd3_pop_asian',
                           'd3_combnd_mosaic_group',
                           'd3_d_est_inc_v5',
                           'd3_length_of_residence',
                           'd3_mor_home_pur_home_pur_1',

                           'd4_married_couple_family',
                           'd4_d1_mfirst',
                           'd4_median_education_attained',
                           'd4_d5_mfirst',
                           'd4_median_family_household_income',
                           'd4_home_owner',
                           'd4_number_of_persons_in_living_unit',
                           'd4_child_hh_with_persons',
                           'd4_median_home_value',
                           'd4_urban_county_size_code',
                           'd4_pop_hispanic',
                           'd4_pop_asian',
                           'd4_combnd_mosaic_group',
                           'd4_d_est_inc_v5',
                           'd4_length_of_residence',
                           'd4_mor_home_pur_home_pur_1',

                           'd5_married_couple_family',
                           'd5_d1_mfirst',
                           'd5_median_education_attained',
                           'd5_d5_mfirst',
                           'd5_median_family_household_income',
                           'd5_home_owner',
                           'd5_number_of_persons_in_living_unit',
                           'd5_child_hh_with_persons',
                           'd5_median_home_value',
                           'd5_urban_county_size_code',
                           'd5_pop_hispanic',
                           'd5_pop_asian',
                           'd5_combnd_mosaic_group',
                           'd5_d_est_inc_v5',
                           'd5_length_of_residence',
                           'd5_mor_home_pur_home_pur_1',

                           'd6_married_couple_family',
                           'd6_d1_mfirst',
                           'd6_median_education_attained',
                           'd6_d5_mfirst',
                           'd6_median_family_household_income',
                           'd6_home_owner',
                           'd6_number_of_persons_in_living_unit',
                           'd6_child_hh_with_persons',
                           'd6_median_home_value',
                           'd6_urban_county_size_code',
                           'd6_pop_hispanic',
                           'd6_pop_asian',
                           'd6_combnd_mosaic_group',
                           'd6_d_est_inc_v5',
                           'd6_length_of_residence',
                           'd6_mor_home_pur_home_pur_1',

                           'd7_married_couple_family',
                           'd7_d1_mfirst',
                           'd7_median_education_attained',
                           'd7_d5_mfirst',
                           'd7_median_family_household_income',
                           'd7_home_owner',
                           'd7_number_of_persons_in_living_unit',
                           'd7_child_hh_with_persons',
                           'd7_median_home_value',
                           'd7_urban_county_size_code',
                           'd7_pop_hispanic',
                           'd7_pop_asian',
                           'd7_combnd_mosaic_group',
                           'd7_d_est_inc_v5',
                           'd7_length_of_residence',
                           'd7_mor_home_pur_home_pur_1',
                         ];
    //
}
